FROM ghcr.io/bell-sw/liberica-runtime-container:jre-25.0.2-slim-stream-musl

WORKDIR /app

# Copy the pre-built zip from build context
COPY artifacts/oocsi-*.zip app.zip

RUN unzip app.zip && \
    mv oocsi* oocsi && \
    rm app.zip

EXPOSE 9000

WORKDIR /app/oocsi
CMD ["bin/oocsi-web", "-Dconfig.file=/app/oocsi/conf/application.conf", "-Dlogger.file=/app/oocsi/conf/logback.xml"]
