FROM ghcr.io/graalvm/graalvm-community:25 AS production

WORKDIR /app

# Copy the pre-built zip from build context
COPY artifacts/oocsi-*.zip app.zip

RUN microdnf install unzip && \
    unzip app.zip && \
    mv oocsi* oocsi && \
    rm app.zip && \
    microdnf remove unzip

EXPOSE 9000

WORKDIR /app/oocsi
CMD ["bin/oocsi-web", "-Dconfig.file=/app/oocsi/conf/application.conf", "-Dlogger.file=/app/oocsi/conf/logback.xml"]
