# This is the main configuration file for the application.
# ~~~~~

oocsi.clients=1000

oocsi.ratelimit.enabled=true
oocsi.ratelimit.capacity=120
oocsi.ratelimit.refillTokens=120
oocsi.ratelimit.refillDurationSeconds=60

play.http.secret.key="change this change this change this"

play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.csp.CSPFilter = "default-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' 'unsafe-inline'; img-src 'self' 'unsafe-inline' data: *; connect-src *;"

play.filters.hosts {
  allowed = ["."]
}
